import * as Activity from './Activity';
import * as Auth from './Auth';
import * as Autoload from './Autoload';
import * as Cookie from './Cookie';
import * as Invite from './Invite';
import * as Form from './Form';
import * as Format from './Format';
import * as LocalStorage from './LocalStorage';
import * as Modal from './Modal';
import * as Reducer from './Reducer';
import * as Route from './Route';
import * as Search from './Search';
import * as Screen from './Screen';
import * as Style from './Style';
import * as Tooltip from './Tooltip';
import * as User from './User';
import * as Utils from './Utils';
import * as WebSocket from './WebSocket';
import * as Window from './Window';
import * as Ymap from './Ymap';

export const sActivity = Activity;
export const sAuth = Auth;
export const sAutoload = Autoload;
export const sCookie = Cookie;
export const sInvite = Invite;
export const sForm = Form;
export const sFormat = Format;
export const sLocalStorage = LocalStorage;
export const sModal = Modal;
export const sReducer = Reducer;
export const sRoute = Route;
export const sSearch = Search;
export const sScreen = Screen;
export const sStyle = Style;
export const sTooltip = Tooltip;
export const sUser = User;
export const sUtils = Utils;
export const sWebSocket = WebSocket;
export const sWindow = Window;
export const sYmap = Ymap;
