import {AboutScreen as _AboutScreen} from './About';
import {ChatScreen as _ChatScreen} from './Chat';
import {ChatUserScreen as _ChatUserScreen} from './ChatUser';
import {ConditionScreen as _ConditionScreen} from './Condition';
import {EventScreen as _EventScreen} from './Event';
import {InviteEditScreen as _InviteEditScreen} from './InviteEdit';
import {InviteViewScreen as _InviteViewScreen} from './InviteView';
import {SearchScreen as _SearchScreen} from './Search';
import {ProfileScreen as _ProfileScreen} from './Profile';
import {ResetPasswordScreen as _ResetPasswordScreen} from './ResetPassword';
import {StartScreen as _StartScreen} from './Start';
import {StaticPageScreen as _StaticPageScreen} from './StaticPage';

export const AboutScreen = _AboutScreen;
export const ChatScreen = _ChatScreen;
export const ChatUserScreen = _ChatUserScreen;
export const ConditionScreen = _ConditionScreen;
export const EventScreen = _EventScreen;
export const InviteEditScreen = _InviteEditScreen;
export const InviteViewScreen = _InviteViewScreen;
export const SearchScreen = _SearchScreen;
export const ProfileScreen = _ProfileScreen;
export const ResetPasswordScreen = _ResetPasswordScreen;
export const StartScreen = _StartScreen;
export const StaticPageScreen = _StaticPageScreen;
